### ISSUE TITLE
[feat] 회원가입 페이지 구현

### ISSUE THREAD

**Issue by prgmr99** [Mall-project-sp/front-end#11]
## 🛠 Issue
- 회원가입 페이지를 구현해주세요.

## 📋 To-do
- [x] 단계별 컴포넌트 구현
- [x] Progress bar 구현
- [x] 이메일 유효성 검사
- [x] 비밀번호 유효성 검사
- [x] 전화번호 자동 하이픈 추가
- [x] 사용자 이름 추가
- [x] 사용자 주소, 서브 주소 추가
- [x] 프로필 사진 createObjectURL로 변경
- [x] 사용자 소개글 추가(필수 입력아님)
- [x] RTK 적용

**Comment by prgmr99** [comment]
프로필 사진 createObjectURL로 변경 -> 백엔드와 상의 후 결정
